
title: My Resume
url: 'http://junlulocky.com'
baseurl: '/CV' #change it according to your repository name



# Profile information
yourname: Brown Smith  ## put your name
title: 'GRAPHIC &amp; WEB DESIGNER'  ## your title
location: San Francisco , CA


## Social Profiles
linkedin: https://www.linkedin.com/in/simon-staehli-468b26168/  ## your linkedin account url
github: https://github.com/SimonStaehli
instagram: https://www.instagram.com/visualframing/
fivehundredpix: https://500px.com/


# Update all the sections by editing the files inside _includes folder.
